function [ z ] = emptyFloorState()
%EMPTYFLOORSTATE structure to analyze user activity with acceletormeter and
% pressure data. Structure updates when vertical distance changes and step
% activity is detected

z = struct('current_steps', 0, ...
    'current_t', 0, ...
    'current_h_cm', 0, ...
    'last_valley_steps', 0, ...
    'last_valley_t', 0, ...
    'last_valley_h_cm', 0, ...
    'last_peak_steps', 0, ...
    'last_peak_t', 0, ...
    'last_peak_h_cm', 0, ...
    'Nfloors', 0);


end

