function [ z ] = emptyAltContextHist(nL)
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('N', 0, ...
    'Nmax',nL, ...
    'lastIndx', 0, ...
    'v', zeros(1, nL), ...
    'context', zeros(1,nL), ...
    'slope', zeros(1,nL));
end