function [ z ] = emptyAltitude()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('schedule',emptySchedule, ...
    'pbData', emptyPBData(ceil(altConsts.pbBufferLength_ms / altConsts.minSample_ms)), ...
    'hist', emptyHist(ceil(altConsts.histLength_ms / altConsts.hist_deltaT)) , ...
    'stanNoise_iir', emptyIIRNoise, ...
    'contextHist', emptyAltContextHist(altConsts.contextHistLen), ...
    'res', emptyAltRes, ...
    'dbg', emptyAltDebug);
end

function [ z ] = emptyAltDebug()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('t', [], ...
    'slope', [], ...
    'h', [], ...
    'dH', [], ...
    'hMax', [], ...
    'maxSlope', [], ...
    'maxRawSlope', [], ...
    'maxdHRate', [], ...
    'context', [], ...
	'steps', [], ...
    'hCal_cm', [],...
    'floor', emptyFloorState, ...
    'Nfloors', []);
end

function [ z ] = emptyPBData(nL)
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('data', emptyProcBuffer(1, nL), ... % here t is for last sample (latest)
    'meanX', 0, ...
    'deltaMx',0);
end

function [ z ] = emptyHist(nL)
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('tRef', 0, ...
    'N', 0, ...
    'Nmax',nL, ...
    'lastIndx', 0, ...
    'v', zeros(1, nL), ...
    'H_cm', zeros(1, nL), ...
    'filt1d', emptyFilterInfo);
end

function [z] = emptyIIRNoise()
z = struct('tRef', 0, ...
    'cSigma',altConsts.min_sigValue); %at stationary
end