function [ z ] = emptyAltRes()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('t', 0, ...
    'valid', 0, ...
    'hBaro_cm', 0, ...
    'hCal_cm', 0, ...
    'uVel', emptySpeedOP, ...
    'context', memsConsts.altContextUnknown, ...
    'contextConf',  memsConsts.confidenceUnknown);
end